### ISSUE TITLE
grey start button (ingame)

### ISSUE THREAD

**Issue by t-500** [DeadlySurprise/FO2-Splitscreen#17]
Hi, maybe its a translation problem, but i do all the steps:
- start launcher.exe (as admin)
- set resolution, 2 controllers
- the game starts (strangely 2 times)
- multiplayer --> LAN --> start as host (i can see only 1 player in the list and the start race butten down right is grey and i cant click it)
- or multiplayer --> LAN --> searching for games --> nothing will found (logically)

Did i forget something?

**Comment by MorMund** [comment]
> the game starts (strangely 2 times)

This is intentional, there is one game window for each player.

After starting the game as host you have to select the second instance of the game and search for games in the LAN menu. Then you should find your host session.

Also make sure to select your controller in settings -> controller options as it usually defaults to keyboard input.

**Comment by t-500** [comment]
Thank you very much for your answer and the great Splitscreen mod.

Cant wait to test it with a buddy.
