### ISSUE TITLE
Another instance fails to connect to the host

### ISSUE THREAD

**Issue by fregys** [DeadlySurprise/FO2-Splitscreen#36]
I am trying running this on Linux and it works to the point when I am trying to connect to already created LAN game by the host. On the other instance the host LAN lobby is visible, but when I try to connect, it fails (asks me to retry or cancel).

I looked in the documentations and it says you are using winsock, so that might be the problem, right? But I don't understand why the lobby is then even visible for the other instance.

**Comment by MorMund** [comment]
Hi @FilipKaspar, thanks for reporting this issue. While I wanted to allow Linux users to use the mod, I have never tested it myself. What version of wine/proton are you using? There might be quirks with how it handles `winsock` connections used by the game. Do you know if the LAN mode works without the mod?

Sadly I don't have much time to work on the mod these days, so it is unlikely I'll debug this soon. But you can try setting the logging to `verbose` in the XML settings file. This should print out a network log. Maybe I can spot the problem and find an easy solution from there.

If it is not easily solvable it might be a "won't fix" from me since I'd like to try to rewrite the network code to use the suggestion mention here instead https://github.com/MorMund/FO2-Splitscreen/issues/28 . Since this modifies less of the network code I hope it also provides better interop on wine/proton.
